import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {BiSearchAlt} from 'react-icons/bi'
import ReactDOM from 'react-dom'
import React from 'react'
import Cover from '../public/content.jpg' ///import fake book cover for books that dont have a book cover


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [searchTerm, setSearchTerm] = React.useState(""); //search state
  const [data, setData] = React.useState([]); //book data from Google books API
  const [info, setInfo] = React.useState(null); //displayed info for book


  const handleChange = event => {
    setSearchTerm(event.target.value);
  }
  const resetInputField = () => {
    setSearchTerm("");
  }
  const fetchBookTitle = async() => {
    const response = await fetch(`https://www.googleapis.com/books/v1/volumes?q=${searchTerm}`);
    const json = await response.json();
    setData(json.items)
  }

  const callSearchFunction = async () => {
    // event.preventDefault; add this and event to the function variable. The method cancels the event if it is canceable, meaning taht the default action that belongs to the event will not occur
    await fetchBookTitle();
    await setInfo([
      // Get this working later using react Image component <Image key="image" src=http://books.google.com/books/content?id=akqQEAAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api width={100} height={100} alt=""/>, //data[0].volumeInfo.imageLinks.smallThumbnail
      <img key="image" className="mx-auto" src={data[0].volumeInfo.imageLinks.thumbnail} alt="no image"></img>,
      <h2 key="title">Title: {data[0].volumeInfo.title}</h2>,
      <h3 key="author">Author: {data[0].volumeInfo.authors}</h3>,
      // <img key="image" className="mx-auto" src={data[1].volumeInfo.imageLinks.thumbnail} alt="no image"></img>,
      // <h2 key="title">Title: {data[1].volumeInfo.title}</h2>,
      // <h3 key="author">Author: {data[1].volumeInfo.authors}</h3>,
      // <img key="image" className="mx-auto" src={data[2].volumeInfo.imageLinks.thumbnail} alt="no image"></img>,
      // <h2 key="title">Title: {data[2].volumeInfo.title}</h2>,
      // <h3 key="author">Author: {data[2].volumeInfo.authors}</h3>,
      // <img key="image" className="mx-auto" src={data[3].volumeInfo.imageLinks.thumbnail} alt="no image"></img>,
      // <h2 key="title">Title: {data[3].volumeInfo.title}</h2>,
      // <h3 key="author">Author: {data[3].volumeInfo.authors}</h3>,
    ]);
    resetInputField();
  }
  return (
    <>
      <Head>
        <title>Between the Lines</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-500">
        <div className="flex justify-around">
          <a href="">Your Books</a>
          <a href="">Your Friends</a>
        </div>
        <div className="flex items-center justify-center h-screen text-gray-600">
          <input type="search" name="search" placeholder="Search" value={searchTerm} onChange={handleChange} class="bg-white h-10 px-5 pr-10 rounded-full text-sm  focus:shadow-lg focus:shadow-slate-900 focus:outline-none"/>
          <button onClick={callSearchFunction} className="bg-transparent text-white font-bold py-2 px-4 rounded flex items-center absolute translate-x-24 hover:scale-110">
            <BiSearchAlt className="w-5 h-5 mr-2 fill-black " />
          </button>
        </div>
        <div className="text-center justify-center text-white">
          {info}
        </div>
      </main>
    </>
  )
}
